"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const user_route_1 = __importDefault(require("../modules/user/user.route"));
const user_flow_route_1 = __importDefault(require("../modules/user-flow/user-flow.route"));
const flow_endpoint_route_1 = __importDefault(require("../modules/flow-endpoint/flow.endpoint.route"));
const schedules_route_1 = __importDefault(require("../modules/schedules/schedules.route"));
const appointments_route_1 = __importDefault(require("../modules/appointments/appointments.route"));
const medical_route_1 = __importDefault(require("../modules/businesses/medical/medical.route"));
const education_route_1 = __importDefault(require("../modules/businesses/education/education.route"));
const student_group_route_1 = __importDefault(require("../modules/student-group/student-group.route"));
const product_route_1 = __importDefault(require("../modules/product/product.route"));
const category_route_1 = __importDefault(require("../modules/category/category.route"));
const campaign_route_1 = __importDefault(require("../modules/campaign/campaign.route"));
const messages_route_1 = __importDefault(require("../modules/messages/messages.route"));
const productCarousel_route_1 = __importDefault(require("../modules/productCarousel/productCarousel.route"));
const orders_route_1 = __importDefault(require("../modules/orders/orders.route"));
const customers_route_1 = __importDefault(require("../modules/customers/customers.route"));
const label_route_1 = __importDefault(require("../modules/label/label.route"));
const router = express_1.default.Router();
router.use("/users", user_route_1.default);
router.use("/user-flow", user_flow_route_1.default);
router.use("/flow-endpoint", flow_endpoint_route_1.default);
router.use("/whatsapp", flow_endpoint_route_1.default);
router.use("/schedule", schedules_route_1.default);
router.use("/appointmenst", appointments_route_1.default);
router.use("/medical-business", medical_route_1.default);
router.use("/education-business", education_route_1.default);
router.use("/student-group", student_group_route_1.default);
router.use("/product", product_route_1.default);
router.use("/campaign", campaign_route_1.default);
router.use("/messages", messages_route_1.default);
router.use("/category", category_route_1.default);
router.use("/orders", orders_route_1.default);
router.use("/customers", customers_route_1.default);
router.use("/product-carousel", productCarousel_route_1.default);
router.use("/label", label_route_1.default);
exports.default = router;
